# Generated by Django 6.0.2 on 2026-02-10 16:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chauffeur',
            name='vehicule',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='web.chauffeur'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entretien',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='web.vehicule'),
        ),
        migrations.CreateModel(
            name='DocumentVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('assurance', 'Assurance'), ('visite', 'Visite technique'), ('carte_grise', 'Carte grise'), ('vignette', 'Vignette'), ('autre', 'Autre')], max_length=50)),
                ('numero_document', models.CharField(max_length=100)),
                ('date_emission', models.DateField()),
                ('date_expiration', models.DateField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents_vehicules/')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web.vehicule')),
            ],
        ),
    ]
