# Generated by Django 6.0.2 on 2026-02-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_chauffeur_vehicule_vehicule_chauffeur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chauffeur',
            name='date_expiration_permis',
        ),
        migrations.RemoveField(
            model_name='chauffeur',
            name='numero_permis',
        ),
        migrations.RemoveField(
            model_name='chauffeur',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='documentvehicule',
            name='date_emission',
        ),
        migrations.RemoveField(
            model_name='documentvehicule',
            name='fichier',
        ),
        migrations.RemoveField(
            model_name='documentvehicule',
            name='numero_document',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='etat',
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='nom',
            field=models.CharField(default='Chauffeur', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('MISSION', 'En mission')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='telephone',
            field=models.CharField(default=90000009, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('MISSION', 'En mission'), ('MAINTENANCE', 'En maintenance')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentvehicule',
            name='type_document',
            field=models.CharField(choices=[('ASSURANCE', 'Assurance'), ('VISITE', 'Visite technique'), ('CARTE_GRISE', 'Carte grise')], max_length=20),
        ),
    ]
