# Generated by Django 6.0.2 on 2026-02-18 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_chauffeur_date_expiration_permis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='date_expiration_permis',
            field=models.DateField(default=datetime.datetime(2026, 2, 18, 17, 20, 16, 653449, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='numero_permis',
            field=models.CharField(default=123456, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
