# Generated by Django 6.0.2 on 2026-02-22 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_chauffeur_date_expiration_permis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_chauffeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
